# Generated by Django 3.2.16 on 2023-01-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
