# Generated by Django 3.2.16 on 2023-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.SmallIntegerField(default=0),
        ),
    ]
