# Generated by Django 3.2.16 on 2023-01-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
