# Generated by Django 3.2.16 on 2023-01-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_myuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
