# Generated by Django 3.2.16 on 2023-01-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
